name: Veracode Demo - SAST - Pipeline
on:
  push:
    branches:
      - pipeline-scan

jobs:
  Build:
    name: Maeven build
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.6-eclipse-temurin-17
      options: --user root
    steps:
      - name: Checkout https://github.com/${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Maeven build
        run: |
          mvn package -DskipTests -f app/pom.xml
      - name: Upload artfacts
        uses: actions/upload-artifact@v4
        with:
          name: artfacts
          path: ${{ vars.TARGET_FILE_PATH }}${{ vars.TARGET_FILE_NAME }}

  Veracode-SAST-Pipeline:
    name: Veracode SAST Pipeline
    runs-on: ubuntu-latest
    needs: [Build]
    strategy:
      fail-fast: true
    env:
      APPLICATION_NAME: Verademo-java-1
      POLICY_NAME: Policy-test-2
    container:
      image: veracode/pipeline-scan:latest
      options: --user root

    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: artfacts
          path: .

      - name: Scan
        run: |
          ## zip -r -v ${{ vars.TARGET_FILE_PATH }} . -i '*.js' '*.html'
          java -jar /opt/veracode/pipeline-scan.jar -vid "${{ secrets.VERACODE_ID }}" -vkey "${{ secrets.VERACODE_KEY }}" -rp "${{ env.POLICY_NAME }}"
          java -jar /opt/veracode/pipeline-scan.jar -vid "${{ secrets.VERACODE_ID }}" -vkey "${{ secrets.VERACODE_KEY }}" -f ${{ vars.TARGET_FILE_NAME }} -p "${{ env.APPLICATION_NAME }}" -pn "${{ env.POLICY_NAME }}"
        continue-on-error: true

      - name: save filtered results file
        uses: actions/upload-artifact@v3
        with:
          name: filtered-results
          path: filtered_results.json