name: Veracode Demo - SCA - Pipeline
on:
  push:
    branches:
      - pipeline-scan

jobs:
  Veracode-SCA:
    name: Veracode SCA
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout https://github.com/${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Archive Release
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        run: |
          export SRCCLR_SCM_REF="${{ github.workflow }}"
          export SRCCLR_SCM_REF_TYPE="branch"
          export SRCCLR_SCM_REV=${{ github.run_id }}
          export SRCCLR_SCM_TYPE="GITHUB"
          export EXTRA_ARGS='--update-advisor --uri-as-name' 
          export SCAN_DIR="./app"
  
          curl -sSL https://download.sourceclear.com/ci.sh | bash -s -- scan $EXTRA_ARGS
        continue-on-error: true